# Generated by Django 5.1.6 on 2025-02-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='payment',
            field=models.CharField(max_length=100),
        ),
    ]
